#!/bin/sh

# The MIT License (MIT)

# Copyright (c) 2015 Kohei Yamamoto.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

if [ $# -ne 1 ]; then
	echo "Usage: ./blgci.sh <entry_id>" 1>&2
	exit 1
fi

which -s git
GIT_EXISTS=$?
if [ $GIT_EXISTS -ne 0 ]; then
    echo "blgci: Git is not installed." 1>&2
    exit 1
fi

if [ ! -e "./.git" ]; then
    echo "blgci: Git repository is not found." 1>&2
    exit 1
fi

FILE_NAME="${1}.md"
if [ ! -e $FILE_NAME ]; then
    echo "blgci: $FILE_NAME is not found." 1>&2
    exit 1
fi

grep -q '<!--.\+-->' $FILE_NAME
TITLE_EXISTS=$?
if [ $TITLE_EXISTS -ne 0 ]; then
    echo "blgci: The title is not included in the file." 1>&2
    echo "       Put \"<!-- [title] -->\" on the first line of the file." 1>&2
    exit 1
fi

ENTRY_TITLE=`head -1 $FILE_NAME | sed 's/^[ ]*//' | sed 's/<!-- //' | sed 's/ -->//' `
ENTRY_URL="http://kymmt90.hatenablog.com/entry/$1"

git add $FILE_NAME
git commit -F - <<EOF
$ENTRY_TITLE

$ENTRY_URL
EOF
